var Lsn88 = {	
	htmlArray: ['<section class="section"><header><h3>LESSON 88: Demonstratives (continued)</h3></header>',
		'<section class="vocab"><h4>Vocabulary</h4><ul><li>umupira - tire, rubber (any kind), sweater (Sw.), rubber eraser</li>',
		'<li>umwanya - time, place, space</li><li>kubura (ze) - to lack, fail, fail to find</li><li>gukira (ze) - to get well, to heal (int.)</li>',
		'<li>none - now</li><li>uruguma - wound, cut</li></ul></section> <!-- end of vocab section -->',
		'<section class="parag"><p>179. Wa, etc. This is the demonstrative which calls attention to that which has been mentioned', 
		'or is well known to both speaker and hearer. (The form is exactly the same as the possessive particle, but it precedes the noun.)</p>',
		'<ul><li>wa mukobga - that girl (as much as to say, "you know the one")</li><li>ca gitabo - that book (which we talked about before)</li></ul>',	
		'</section>  <!-- end of paragraph section -->',
		'<section class="parag"><p>180. Uno. The forms in this column you need to be able to recognize. They mean practically the same as', 
		'uyu, but they are not altogether interchangeable. So, for the present, be able to recognize these but do not try to use them.</p>',
		'<p> Nya. There exists this one other demonstrative nya, which is invariable and is usually used only with the singular. Its use is similar to that of uwo. etc.</p>',
		'<ul><li>Nya muntu,</li><li>nya gitabo</li></ul></section>  <!-- end of paragraph section --><section class="parag">',	
		'<p>181. Kubura. In addition to the meanings given in this vocabulary, this word is used in the future negative to express the idea of certainty. e.g.</p>',
		'<ul><li>Ntazobura kugenda - he will certainly go (lit. he will not fail to go}</li></ul></section>  <!-- end of paragraph section -->',
		'<section class="parag"><p>182. Umwanya. This word and igihe, which also means time, are not used interchangeably.', 
		'Igihe means time in the sense of days, weeks, years, etc. while umwanya means time in the sense of space of time. Sometimes it is used like uburyo. e.g.</p>',
		'<ul><li>Simfise umwanya wo kugikora - I haven~t time to do it.</li></ul><p>Also, unwanya has the other meanings as given in the vocabulary.</p>',
		'<ul><li>Mu mwanya wo gusoma, abana bicara neza. - At reading time (time to read) the children sit quietly.</li><li>Ntidufise umwanya wo kukujana. - We don\'t have room (space) to take you.</li></ul>',	
		'</section>  <!-- end of paragraph section --><section class="exer"><h4>Exercises:</h4><section><h5>I.Translate into English</h5>',
		'<ol><li><p>Rwa ruguma rubi rwakize neza.</p><p></p></li><li><p>Umwigisha ntazobura guhana ba bana babi.</p><p></p></li>',
		'<li><p>Wa musore ntafise umwanya wo kurondera ca gitabo.</p><p></p></li><li><p>Imbga zishe ka kayabo kacu; non\' imbeba nyinshi zizoza.</p><p></p></li>',
		'<li><p>Mbega wibutse kuzana ya mafaranga? Oya, nayibagiye.</p><p></p></li><li><p>Yesu azotujana mw ijuru kugira ngo tubone bga bgiza bgiwe.</p><p></p></li',
		'<li><p>Mbega wabonye ya mbugita yawe? Oya, nayibuze.</p><p></p></li><li><p>Mbega mutinya iki? Kwa kwizera kwanyu kuri hehe?</p><p></p></li>',
		'<li><p>Wa mwana arizwa n\'iki? Ararira kuko yabuze ya mbga yiwe.</p><p></p></li><li><p>Genda wanure za ngano, uzishire mu masaho.</p><p></p></li>',
		'</ol></section><section><h5>II. Translate into Kirundi</h5><ol><li><p>The boy\'s parents prevented him from bringing (to bring) those sweet potatoes.</p><p></p></li>',
		'<li><p>That bad tire is flat (is dead); we will be late to go.</p><p></p></li><li><p>Where are those medicines? The people want them.</p><p></p></li>',
		'<li><p>Did you take those seeds? I do not see them.</p><p></p></li><li><p>That thief came again in the night; let us catch him.</p><p></p></li>',
		'<li><p>Yesterday that foolish man came back here. Can\'t the doctor heal him?</p><p></p></li><li><p>Where is that machete you cut grass with yesterday?</p><p></p></li>',
		'<li><p>The doctor has treated well your father\'s wounds. He will certainly get well.</p><p></p></li><li><p>Will you take me to Bujumbura? I\'m sorry (see Lesson 46), I don\'t have room.</p><p></p></li>',
		'<li><p>When will those workmen be paid their francs? I\'ll give them to them on May 3rd.</p>',
		'<p></p></li></ol></section></section>  <!-- end of exer section --></section> <!-- end of chap section -->']
}	